# Generated by Django 4.2.30 on 2026-06-19 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('APROVADO', 'Aprovado'), ('NEGADO', 'Negado')], max_length=10)),
                ('username_solicitante', models.CharField(max_length=150)),
                ('email_solicitante', models.CharField(blank=True, max_length=254)),
                ('tipo_solicitado', models.CharField(max_length=20)),
                ('data_acao', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_acao'],
            },
        ),
    ]
