# Generated by Django 4.2.30 on 2026-06-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_historicoacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('NOTEBOOK', 'Notebook'), ('TABLET', 'Tablet'), ('CELULAR', 'Celular'), ('PROJETOR', 'Projetor'), ('OUTRO', 'Outro')], default='NOTEBOOK', max_length=20)),
                ('quantidade', models.PositiveIntegerField(default=1, help_text='Quantidade total disponível')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('localizacao', models.CharField(blank=True, max_length=100, verbose_name='Localização')),
                ('capacidade', models.PositiveIntegerField(default=0, help_text='Número de alunos')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['nome'],
            },
        ),
    ]
