# Generated by Django 4.2.30 on 2026-06-24 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_turma_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('aula', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('SALA', 'Sala de Aula'), ('DISPOSITIVO', 'Equipamentos Móveis')], max_length=12)),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='app.sala')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='app.turma')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['data', 'aula'],
            },
        ),
    ]
