# Generated by Django 4.2.30 on 2026-06-25 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_itemdispositivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacaoAlunoEquipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.CharField(blank=True, help_text='Identificação do equipamento com o aluno (ex.: C13)', max_length=100)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacoes', to='app.agendamento')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacoes', to='app.aluno')),
            ],
            options={
                'verbose_name': 'Relação aluno/equipamento',
                'verbose_name_plural': 'Relações aluno/equipamento',
                'unique_together': {('agendamento', 'aluno')},
            },
        ),
    ]
