# Generated by Django 4.2.30 on 2026-06-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_relacaoalunoequipamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamento',
            options={'ordering': ['categoria', 'apelido'], 'verbose_name': 'Equipamento', 'verbose_name_plural': 'Equipamentos'},
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='itemdispositivo',
            name='equipamento',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='apelido',
            field=models.CharField(default='', help_text='Ex: C01, CH03', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='categoria',
            field=models.CharField(choices=[('NOTEBOOK', 'Notebooks'), ('CHROMEBOOK', 'Chromebooks'), ('DESKTOP', 'Desktops'), ('TABLET', 'Tablets'), ('SMARTPHONE', 'Smartphones')], default='NOTEBOOK', max_length=15),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='foto_dados',
            field=models.BinaryField(blank=True, max_length='max', null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='foto_mime',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='identificacao_escola',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Identificação da escola'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='imei',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IMEI'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='numero_patrimonio',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Número de patrimônio'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='numero_serie',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Número de série'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('MANUTENCAO', 'Em manutenção'), ('QUEBRADO', 'Quebrado'), ('DESATIVADO', 'Desativado')], default='ATIVO', max_length=12),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='tem_foto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemdispositivo',
            name='categoria',
            field=models.CharField(choices=[('NOTEBOOK', 'Notebooks'), ('CHROMEBOOK', 'Chromebooks'), ('DESKTOP', 'Desktops'), ('TABLET', 'Tablets'), ('SMARTPHONE', 'Smartphones')], default='NOTEBOOK', max_length=15),
        ),
    ]
