# Generated by Django 4.2.30 on 2026-06-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_equipamento_options_remove_equipamento_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='categoria',
            field=models.CharField(choices=[('NOTEBOOK', 'Notebook'), ('CHROMEBOOK', 'Chromebook'), ('DESKTOP', 'Desktop'), ('TABLET', 'Tablet'), ('SMARTPHONE', 'Smartphone')], default='NOTEBOOK', max_length=15),
        ),
        migrations.AlterField(
            model_name='itemdispositivo',
            name='categoria',
            field=models.CharField(choices=[('NOTEBOOK', 'Notebook'), ('CHROMEBOOK', 'Chromebook'), ('DESKTOP', 'Desktop'), ('TABLET', 'Tablet'), ('SMARTPHONE', 'Smartphone')], default='NOTEBOOK', max_length=15),
        ),
    ]
