# Generated by Django 4.2.30 on 2026-06-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_equipamento_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='observacao',
            field=models.TextField(blank=True, default='', help_text='Anotações sobre o equipamento, histórico de problemas, etc.', verbose_name='Observação'),
        ),
    ]
