# Generated by Django 4.2.30 on 2026-07-06 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_equipamento_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoacao',
            name='acao',
            field=models.CharField(choices=[('APROVADO', 'Aprovado'), ('NEGADO', 'Negado'), ('ATIVADO', 'Conta ativada'), ('DESATIVADO', 'Conta desativada'), ('PROMOVIDO', 'Promovido a admin'), ('REBAIXADO', 'Rebaixado a professor'), ('REDEFINIDO', 'Senha redefinida')], max_length=20),
        ),
        migrations.CreateModel(
            name='PedidoRedefinicaoSenha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendido', models.BooleanField(default=False)),
                ('atendido_em', models.DateTimeField(blank=True, null=True)),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redefinicoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_senha', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido de redefinição de senha',
                'verbose_name_plural': 'Pedidos de redefinição de senha',
                'ordering': ['-criado_em'],
            },
        ),
    ]
