# Generated by Django 4.2.30 on 2026-08-20 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_historicoacao_acao_pedidoredefinicaosenha'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='fixo',
            field=models.BooleanField(default=False, help_text='Indica se o equipamento é fixo em uma sala', verbose_name='Fixo'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='sala',
            field=models.ForeignKey(blank=True, help_text='Selecione a sala caso o equipamento seja fixo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos_fixos', to='app.sala', verbose_name='Sala onde é fixo'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='foto_dados',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicoacao',
            name='acao',
            field=models.CharField(choices=[('APROVADO', 'Aprovado'), ('NEGADO', 'Negado'), ('ATIVADO', 'Conta ativada'), ('DESATIVADO', 'Conta desativada'), ('PROMOVIDO', 'Promovido a admin'), ('REBAIXADO', 'Rebaixado a professor'), ('REDEFINIDO', 'Senha redefinida'), ('SENHA_CANCELADA', 'Pedido de senha cancelado'), ('AGENDOU', 'Agendamento realizado'), ('ALTEROU_AGENDAMENTO', 'Agendamento alterado'), ('CANCELOU_AGENDAMENTO', 'Agendamento cancelado')], max_length=25),
        ),
    ]
