# Generated by Django 4.2.30 on 2026-08-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_equipamento_fixo_equipamento_sala_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicoacao',
            options={'ordering': ['-data_acao'], 'verbose_name': 'Histórico de Ação', 'verbose_name_plural': 'Histórico de Ações'},
        ),
        migrations.AlterModelOptions(
            name='itemdispositivo',
            options={'verbose_name': 'Item de Dispositivo', 'verbose_name_plural': 'Itens de Dispositivos'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['data', 'aula', 'tipo'], name='app_agendam_data_14287d_idx'),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['professor', 'data'], name='app_agendam_profess_316e9c_idx'),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['turma', 'nome'], name='app_aluno_turma_i_0c8e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['ra'], name='app_aluno_ra_3ac503_idx'),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['status', 'fixo', 'categoria'], name='app_equipam_status_37d691_idx'),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['apelido'], name='app_equipam_apelido_2143f9_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoacao',
            index=models.Index(fields=['-data_acao'], name='app_histori_data_ac_b01ebb_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoacao',
            index=models.Index(fields=['acao'], name='app_histori_acao_29e7fe_idx'),
        ),
        migrations.AddIndex(
            model_name='itemdispositivo',
            index=models.Index(fields=['agendamento', 'categoria'], name='app_itemdis_agendam_ef7a01_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoredefinicaosenha',
            index=models.Index(fields=['atendido', '-criado_em'], name='app_pedidor_atendid_bf6bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='perfil',
            index=models.Index(fields=['aprovado', 'tipo'], name='app_perfil_aprovad_8ae333_idx'),
        ),
        migrations.AddIndex(
            model_name='sala',
            index=models.Index(fields=['ativo', 'nome'], name='app_sala_ativo_c49358_idx'),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'SALA')), fields=('data', 'aula', 'sala'), name='unique_reserva_sala_aula_data'),
        ),
    ]
