# Generated by Django 4.2.30 on 2026-08-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_add_indexes_and_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
