# Generated by Django 4.2.30 on 2026-08-26 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_alter_turma_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.AddField(
            model_name='agendamento',
            name='fixo',
            field=models.BooleanField(default=False, help_text='Agendamento fixo semanal'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='fixo_grupo_id',
            field=models.CharField(blank=True, default='', help_text='UUID que agrupa agendamentos fixos do mesmo conjunto', max_length=36),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['fixo_grupo_id'], name='app_agendam_fixo_gr_fb30cc_idx'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['destinatario', 'lida', '-criada_em'], name='app_notific_destina_99c71d_idx'),
        ),
    ]
