# Generated by Django 4.2.30 on 2026-08-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_notificacao_agendamento_fixo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto_dados',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto_mime',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tem_foto',
            field=models.BooleanField(default=False),
        ),
    ]
