# Generated by Django 4.2.30 on 2026-08-28 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_perfil_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensagem de Chat',
                'verbose_name_plural': 'Mensagens de Chat',
                'ordering': ['data_envio'],
                'indexes': [models.Index(fields=['remetente', 'destinatario'], name='app_mensage_remeten_53d028_idx'), models.Index(fields=['destinatario', 'lida'], name='app_mensage_destina_38b21d_idx'), models.Index(fields=['data_envio'], name='app_mensage_data_en_3c0179_idx')],
            },
        ),
    ]
