# Generated by Django 4.2.30 on 2026-09-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_mensagemchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='imei_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IMEI 2'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='modelo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='imei',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IMEI 1'),
        ),
    ]
