# Generated by Django 4.2.30 on 2026-09-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_equipamento_imei_2_equipamento_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='digito',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Dígito'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='uf',
            field=models.CharField(blank=True, default='SP', max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='ra',
            field=models.CharField(max_length=30, verbose_name='RA (registro)'),
        ),
    ]
