# Generated by Django 4.2.30 on 2026-09-17 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_aluno_digito_aluno_uf_alter_aluno_ra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('preenchido_em', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Relação',
                'verbose_name_plural': 'Relações',
                'ordering': ['-preenchido_em', '-criado_em'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='relacaoalunoequipamento',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='relacaoalunoequipamento',
            name='agendamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relacoes', to='app.agendamento'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='relacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='app.relacao'),
        ),
        migrations.AddField(
            model_name='relacaoalunoequipamento',
            name='relacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app.relacao'),
        ),
    ]
