# Generated by Antigravity on 2026-09-17

from django.db import migrations


def migrar_relacoes_agendamentos(apps, schema_editor):
    Agendamento = apps.get_model('app', 'Agendamento')
    Relacao = apps.get_model('app', 'Relacao')
    RelacaoAlunoEquipamento = apps.get_model('app', 'RelacaoAlunoEquipamento')

    agendamentos = list(Agendamento.objects.order_by('data', 'professor_id', 'turma_id', 'aula'))

    # Dicionário para rastrear a relação atribuída a (data, professor_id, turma_id, aula)
    mapa_aulas = {}

    for ag in agendamentos:
        chave_base = (ag.data, ag.professor_id, ag.turma_id)
        # Verifica se a aula anterior (aula - 1) do mesmo professor/turma/data já possui relação
        aula_ant = ag.aula - 1
        relacao_existente = mapa_aulas.get((chave_base, aula_ant))

        if relacao_existente:
            rel = relacao_existente
        else:
            rel = Relacao.objects.create()

        ag.relacao = rel
        ag.save(update_fields=['relacao'])
        mapa_aulas[(chave_base, ag.aula)] = rel

    # Migra os itens de RelacaoAlunoEquipamento para apontar para a relacao do agendamento
    for item in RelacaoAlunoEquipamento.objects.filter(agendamento__isnull=False):
        if item.agendamento and item.agendamento.relacao:
            item.relacao = item.agendamento.relacao
            item.save(update_fields=['relacao'])

    # Atualiza o status preenchido_em de todas as relações
    for rel in Relacao.objects.all():
        tem_itens = RelacaoAlunoEquipamento.objects.filter(relacao=rel, equipamento__gt='').exists()
        if tem_itens:
            primeiro_item = RelacaoAlunoEquipamento.objects.filter(relacao=rel, equipamento__gt='').first()
            if primeiro_item and primeiro_item.agendamento:
                rel.preenchido_em = primeiro_item.agendamento.criado_em
            else:
                from django.utils import timezone
                rel.preenchido_em = timezone.now()
            rel.save(update_fields=['preenchido_em'])


def reverter_migracao(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_relacao_and_more'),
    ]

    operations = [
        migrations.RunPython(migrar_relacoes_agendamentos, reverter_migracao),
    ]
