# Generated by Django 4.2.30 on 2026-09-17 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0021_vincular_relacoes_existentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_fato', models.DateTimeField(verbose_name='Data e Horário do Fato')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='app.agendamento', verbose_name='Aula / Agendamento')),
                ('alunos', models.ManyToManyField(blank=True, related_name='ocorrencias', to='app.aluno', verbose_name='Alunos Envolvidos')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado Por')),
                ('equipamentos', models.ManyToManyField(blank=True, related_name='ocorrencias', to='app.equipamento', verbose_name='Equipamentos Envolvidos')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_professor', to=settings.AUTH_USER_MODEL, verbose_name='Professor Responsável')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['-data_hora_fato', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='ocorrencias/%Y/%m/', verbose_name='Foto')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='app.ocorrencia', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name': 'Foto da Ocorrência',
                'verbose_name_plural': 'Fotos da Ocorrência',
                'ordering': ['criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='ocorrencia',
            index=models.Index(fields=['-data_hora_fato'], name='app_ocorren_data_ho_54d008_idx'),
        ),
        migrations.AddIndex(
            model_name='ocorrencia',
            index=models.Index(fields=['agendamento'], name='app_ocorren_agendam_bfb1de_idx'),
        ),
        migrations.AddIndex(
            model_name='ocorrencia',
            index=models.Index(fields=['professor'], name='app_ocorren_profess_65afa0_idx'),
        ),
        migrations.AddIndex(
            model_name='ocorrencia',
            index=models.Index(fields=['criado_por'], name='app_ocorren_criado__204bed_idx'),
        ),
    ]
